pwd:=getwd()
src_path:=join_path(pwd,'src','')
vls_112_source_path := join_path(src_path,'vls-112.v')
vls_112_exec_path := join_path(pwd,'vls-112')
system(@VEXE + ' -prod "$vls_112_source_path" -o "$vls_112_exec_path"')